[features]
seeds = false
skip-lint = false
[programs.localnet]
d_twitter = "EC2LNXS6fWRpiwfDEd8bRVbxK5621Z7XdhhSTvj8oveP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
