name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  SOLANA_VERSION: v1.9.9
  ANCHOR_VERSION: 0.24.2
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Use Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: "npm"
